prefix cpmeta: <http://meta.icos-cp.eu/ontologies/cpmeta/>
construct{
	?dobj cpmeta:hasKeywords "Drought 2018"^^xsd:string .
}
where{
	?dobj cpmeta:hasObjectSpec <http://meta.icos-cp.eu/resources/cpmeta/drought2018FluxnetProduct>
}
