prefix prov: <http://www.w3.org/ns/prov#>
prefix cpmeta: <http://meta.icos-cp.eu/ontologies/cpmeta/>
construct{
	?acq cpmeta:wasPerformedWith ?instr
}
from <http://meta.icos-cp.eu/resources/icos/>
from <http://meta.icos-cp.eu/resources/etcmulti/>
where{
	?dobj cpmeta:wasSubmittedBy/prov:wasAssociatedWith/a cpmeta:ES ;
		cpmeta:wasAcquiredBy ?acq .
	?acq cpmeta:wasPerformedWith ?instr .
}
