prefix cpmeta: <http://meta.icos-cp.eu/ontologies/cpmeta/>
construct {
?dobj cpmeta:hasDoi ?doi .
} where{
   ?dobj cpmeta:hasObjectSpec <http://meta.icos-cp.eu/resources/cpmeta/drought2018FluxnetProduct> .
	?dobj cpmeta:hasDoi ?doi .
}

