prefix cpmeta: <http://meta.icos-cp.eu/ontologies/cpmeta/>
prefix prov: <http://www.w3.org/ns/prov#>
construct{
    ?dobj ?pred ?obj .
        ?obj ?pred2 ?obj2 .
}
FROM <http://meta.icos-cp.eu/resources/otcprodcsv/>
where {
	?dobj cpmeta:wasSubmittedBy ?subm .
	FILTER NOT EXISTS {?subm prov:endedAtTime ?size } .
	?dobj ?pred ?obj .
	OPTIONAL{
		?obj ?pred2 ?obj2 .
		FILTER(?pred != cpmeta:isNextVersionOf )
	}
}

