prefix cpmeta: <http://meta.icos-cp.eu/ontologies/cpmeta/>
construct {
?dobj ?p ?o .
?o ?p2 ?o2 .
} where{
	values ?dobj {
		<https://meta.icos-cp.eu/objects/y-gEd0Ce9MyzrvEg0L1LPpxQ>
	}
	graph <http://meta.icos-cp.eu/resources/otcprodcsv/> {
		?dobj ?p ?o .
		OPTIONAL{
			?o ?p2 ?o2 .
			FILTER(?p != cpmeta:isNextVersionOf)
		}
	}
}

