prefix cpmeta: <http://meta.icos-cp.eu/ontologies/cpmeta/>
construct{
	?s cpmeta:hasDocumentationObject ?olddoc .
}
where{
	?s a cpmeta:AS .
	?s cpmeta:hasDocumentationObject ?olddoc .
	filter exists{[] cpmeta:isNextVersionOf ?olddoc}
}

	#?s cpmeta:hasDocumentationObject ?newest .
	#?newest cpmeta:isNextVersionOf+ ?olddoc .
	#filter not exists{[] cpmeta:isNextVersionOf ?newest}
