prefix cpmeta: <http://meta.icos-cp.eu/ontologies/cpmeta/>
prefix prov: <http://www.w3.org/ns/prov#>

select ?column where{
  VALUES ?columnName { "n2o" }
  ?column cpmeta:hasColumnTitle ?columnName .
}
