prefix cpmeta: <http://meta.icos-cp.eu/ontologies/cpmeta/>
prefix prov: <http://www.w3.org/ns/prov#>

select ?obj ?name ?hasNumberOfRows ?hasSizeInBytes ?hasDoi ?hasKeyword
  where{
    ?obj cpmeta:hasObjectSpec ?spec .
    ?obj cpmeta:hasName ?name .
    ?obj cpmeta:hasSha256sum ?hash .
    ?obj cpmeta:hasNumberOfRows ?hasNumberOfRows .
    ?obj cpmeta:hasDoi ?hasDoi .
    ?obj prov:wasProducedBy ?produced .
    ?obj cpmeta:hasSizeInBytes ?hasSizeInBytes .
  }
  LIMIT 100000
