prefix cpmeta: <http://meta.icos-cp.eu/ontologies/cpmeta/>
prefix prov: <http://www.w3.org/ns/prov#>

select ?dataset where{
	?dataset cpmeta:hasColumn ?column .
	?column cpmeta:hasColumnTitle ?columnName .
}
