prefix cpmeta: <http://meta.icos-cp.eu/ontologies/cpmeta/>
prefix prov: <http://www.w3.org/ns/prov#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?object ?spec where{
  ?object cpmeta:hasObjectSpec ?specUri .
  ?specUri rdfs:label ?spec .
  filter contains(?spec, "CO2 data")
}
