services:
  db:
    container_name: rdfsql
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=ontop
    ports:
      - 65432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: >
        -c max_wal_size=8GB
        -c synchronous_commit=off


  ontop:
    tty: true
    stdin_open: true
    image: rdfsql-ontop
    volumes:
      - .:/source
    build:
      context: .
      dockerfile: Dockerfile
