# docker-compose.yml
version: '3'
services:

    fdp:
        container_name: fdp17
        image: fairdata/fairdatapoint:1.17.2
        volumes:
            - ./application.yml:/fdp/application.yml:ro
            - ./rdfdata:/fdp/rdfdata

    fdp-client:
        container_name: fdp_client17
        image: fairdata/fairdatapoint-client:1.17.0
        ports:
            - 127.0.0.1:8085:80
        environment:
            - FDP_HOST=fdp

    mongo:
        container_name: fdp_mongo17
        image: mongo:4.2.24
        volumes:
            - ./mongodata:/data/db
