version: '3'
services:

    fdp:
        container_name: fdp
        image: fairdata/fairdatapoint:develop
        volumes:
            - ./application.yml:/fdp/application.yml:ro
            - ./rdfdata:/fdp/rdfdata

    fdp-client:
        container_name: fdp_client
        image: fairdata/fairdatapoint-client:1.17.0
        ports:
            - 127.0.0.1:8085:80
        environment:
            FDP_HOST: fdp



    postgres:
        container_name: fdp_postgres
        image: postgres:15.8
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: fdp
        volumes:
            - ./pgdata:/var/lib/postgresql/data
