prefix cpmeta: <http://meta.icos-cp.eu/ontologies/cpmeta/>
prefix prov: <http://www.w3.org/ns/prov#>
select *
where {
?dobj cpmeta:wasAcquiredBy/prov:startedAtTime ?startTime .
?dobj cpmeta:hasName ?fileName .
}

